desapego/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('doeja.urls.AuthUrls')),
    path('', include('doeja.urls.HomeUrls')),
    path('profile/', include('doeja.urls.ProfileUrls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

doeja/models/Donations.py
from doeja.models import *


class Donation(TimestampedModel):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    name_of_object = models.CharField(max_length=100, null=True, blank=True)
    description = models.CharField(max_length=255, null=True, blank=True)
    date_of_donation = models.DateField(default=None, null=True, blank=True)
    status = models.IntegerField(choices=DONATION_STATUS, default=1)
    picture = models.ImageField(null=True, blank=True)
    category = models.IntegerField(choices=CATEGORY_CHOICES, default=1)
    likes = models.ManyToManyField(User, related_name='likes', blank=True)
    
    def __str__(self):
        return f'{self.name_of_object} - {self.category}'
    
class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    donation = models.ForeignKey(Donation, on_delete=models.CASCADE)

doeja/models/Profile.py
from doeja.models import *
from .Timestamp import TimestampedModel

class Profile(TimestampedModel):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    role = models.IntegerField(choices=ROLE_CHOICE, default=3)
    birthday = models.DateField(default=None, null=True, blank=True)
    picture = models.ImageField(null=True, blank=True)
    token = models.CharField(max_length=255, null=True, blank=True)
    
    def __str__(self):
        return '{}'.format(self.user.username)
    
    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        try:
            if created:
                Profile.objects.create(user=instance)
        except:
            pass
        
    
    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        try:
            instance.profile.save()
        except:
            pass
        

doeja/models/Timestamp.py
from doeja.models import *

class TimestampedModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

doeja/forms/AuthForm.py
from django import forms
class LoginForm(forms.Form):
    username = forms.CharField(
        required=True, 
        widget=forms.TextInput(attrs={'class': 'input-field, left-align'}),
        label="Usuário"
        )
    password = forms.CharField(
        max_length=32,
        widget=forms.PasswordInput(
            attrs={'class': 'input-field,left-align'}
        ),
        required=True, 
        label='Senha'
    )
    
class RegisterForm(forms.Form):
    username = forms.CharField(required=True)
    email  = forms.CharField(required=True)
    password = forms.CharField(max_length=32)
    role = forms.ChoiceField(
        choices=(
            (2, 'Doador'),
            (3, 'Receptor'),
        ),
        widget=forms.RadioSelect(attrs={'class': 'form-check-input'}),
        required=True,
        label='',
    )

doeja/forms/DonationForm.py
from django import forms
from doeja.models import Donation

class DonationForm(forms.ModelForm):
    class Meta:
        model = Donation
        fields = (
            'name_of_object',
            'description',
            'status',
            'picture',
            'category',
        )

doeja/views/AuthView.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from doeja.forms.AuthForm import LoginForm, RegisterForm



def login_view(request):
    loginForm = LoginForm()
    message = None
    
    if request.user.is_authenticated:
        return redirect('/')
    
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        loginForm = LoginForm(request.POST)
        
        if loginForm.is_valid():
            user = authenticate(username=username, password=password)
            
            if user is not None:
                login(request, user)
                return redirect('/')
            else:
                message = {
                    'color' : 'red',
                    'text' : 'Dados de usuário incorrectos'
                }
                
    context = {
        'form' : loginForm,
        'message' : message,
        'button_text' : 'Login'
    }
        
    return render(
        request,
        template_name='auth/auth.html',
        context=context,
        status=200
    )
    
def register_view(request):
    registerForm = RegisterForm()
    message = None
    
    if request.user.is_authenticated:
        return redirect('/')
    
    if request.method == 'POST':
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        role = request.POST['role']
        registerForm = RegisterForm(request.POST)
        
        if registerForm.is_valid():
            # verify that user exist
            verify_username = User.objects.filter(username=username).first()
            verify_email = User.objects.filter(email=email).first()
            
            if verify_username is not None:
                message = {
                    'type' : 'danger',
                    'text' : 'Já existe um usuário com este username!!'
                }
            
            elif verify_email is not None:
                message = {
                    'color': 'red',
                    'text' : 'Já existe um usuário com este e-mail!!'
                }
            else:
                user = User.objects.create_user(username, email, password)
                profile = user.profile
                profile.role = role
                profile.save()
                if user is  not None:
                    message = {
                        'color': 'teal',
                        'text': 'Conta criada com sucesso!'
                    }
                    redirect('login/')
                else:
                    message = {
                        'type': 'danger',
                        'text': 'Um erro ocorreu ao tentar criar a conta'
                    }
                    
    context = {
        'form' : registerForm,
        'message': message,
        'title' : 'Registrar',
        'button_text' : 'Registrar'
    }
    
    return render(request, template_name='auth/auth.html', context=context, status=200)
        
def logout_view(request):
    logout(request)
    return redirect('/auth/login')

doeja/views/HomeView.py
from django.shortcuts import get_object_or_404, redirect, render, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from doeja.forms.DonationForm import DonationForm
from doeja.models import Donation, Profile
from django.core.paginator import Paginator

def list_donation_view(request):
    name_of_object = request.GET.get("name_of_object")
    description = request.GET.get('description')
    date_of_donation = request.GET.get('date_of_donation')
    status = request.GET.get('status')
    picture = request.GET.get('picture')
    category = request.GET.get('category')
    
    donations_list = Donation.objects.all().order_by('-created_at')
    
    if name_of_object is not None:
        donations = donations.filter(name_of_object__icontains=name_of_object)
    if description is not None:
        donations = donations.filter(description__id=description)
    if date_of_donation is not None:
        donations = donations.filter(date_of_donation__id=date_of_donation)
    if status is not None:
        donations = donations.filter(status__id=status)
    if picture is not None:
        donations = donations.filter(picture__id=picture)
    if category is not None:
        donations = donations.filter(category__id=category)
        

    paginator = Paginator(donations_list , 8 )
    page = request.GET.get("page")
    donations = paginator.get_page(page)
        
    context={
        'donations' : donations
    }
    
    return render(
        request, template_name='home/home.html', context=context
    )
    

def see_and_contact(request, id):
    donations = Donation.objects.filter(id=id)
    context = {
        'donations': donations
    }
    return render(
        request,
        template_name='home/contact.html',
        context=context
            
    )
    
    
@login_required
def own_donation(request):
    if request.method == 'POST':
        form = DonationForm(request.POST, request.FILES)
        if form.is_valid():
            donation = form.save(commit=False)
            donation.user = request.user.profile
            donation.save()
            return redirect('own_donation')
    else:
        form = DonationForm()

    user = Profile.objects.get(user=request.user)
    donations = Donation.objects.filter(user=user).order_by('-created_at')

    context = {
        'donations': donations,
        'form': form,
    }
    
    return render(request, template_name='home/own_donation.html', context=context)

@login_required
def delete_donation(request, id):
    donation = get_object_or_404(Donation, pk=id)
    donation.delete()
    return redirect('own_donation')

@login_required
def edit_donation(request, id):
    donation = get_object_or_404(Donation, pk=id)

    if request.method == "POST":
        form = DonationForm(request.POST, request.FILES, instance=donation)
        if form.is_valid():
            updated_donation = form.save(commit=False)
            updated_donation.user = request.user.profile
            updated_donation.save()
            return redirect('own_donation')
    else:
        form = DonationForm(instance=donation)

    context = {'form': form, 'donation': donation}
    return render(
        request,
        template_name='home/edit-donation.html',
        context=context
    )
        
# view to like donation
def like_donation(request, donation_id):
    donation = get_object_or_404(Donation, pk=donation_id)
    
    if request.user in donation.likes.all():
        donation.likes.remove(request.user)
    else:
        donation.likes.add(request.user)
        
        
    return redirect(
        'home'
    )

doeja/views/ProfileView.py
from django.http import HttpResponse


def list_profile_view(request):
    return HttpResponse('<h1>Perfil do usuario</h1>')

doeja/templates/home/contact.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Detalhes
{% endblock title %}


{% block content %}
<div class="container">
    <div class="row">
        {% for donation in donations %}
        <div class="col m6">
            <div class="card">
                {% if donation.picture %}
                <div class="card-image">
                    <img src="{{ donation.picture.url }}" alt="{{ donation.name_of_object }}">
                </div>
                {% endif %}
                <div class="card-action">
                    <span class="text-black h3" style="font-weight: bold; font-size: 28px;">{{ donation.name_of_object }}</span>
                    <p>{{ donation.description }}</p>
                </div>
                <div class="card-action">
                    <span>Categoria: {{ donation.get_category_display }}</span>
                    <span class="right">{{ donation.created_at|date:"d/m/Y" }}</span>
                </div>
                {% if user.is_authenticated %}
                <div class="card-action">
                    <a href="{% url 'like_donation' donation_id=donation.id %}">
                        <span class="right">{{ donation.likes.count }} Likes</span>
                    </a>
                </div>
                {% endif %}
            </div>
        </div>
        <div class="col m6">
            <h2 class="subtitulo">Entrar em Contacto</h2>
            <div>
                
                {% if donation.user.picture %}
                    <img class="responsive-img circle" src="{{donation.user.picture.url}}" style="width: 200px; margin-bottom: 20px;">
                {% else %}
                    <img class="responsive-img circle" src="{% static 'img/default.jpg' %}" style="width: 200px; margin-bottom: 20px;">  
                {% endif %}
                    
                <p>Doador: {{donation.user}}</p>
                <p>Status: {{donation.get_status_display }}</p>
            </div>
            <div class="row">
                <form class="col s12">
                  <div class="row">
                    <div class="input-field col s6">
                      <input placeholder="Placeholder" id="first_name" type="text" class="validate">
                      <label for="first_name">First Name</label>
                    </div>
                    <div class="input-field col s6">
                      <input id="last_name" type="text" class="validate">
                      <label for="last_name">Last Name</label>
                    </div>
                  </div>
                  <div class="row">
                    <form class="col s12">
                      <div class="row">
                        <div class="input-field col s12">
                          <textarea id="textarea1" class="materialize-textarea"></textarea>
                          <label for="textarea1">Messagem</label>
                        </div>
                      </div>
                    </form>
                  </div>                
                  </div>
                </form>
              </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}
    

doeja/templates/home/edit-donation.html
{% extends 'base.html' %}
{% block title %}
    Editar
{% endblock title %}


{% block content %}
{% if user.is_authenticated %}
<div class="col">
    <div class="container">
    <h5 class="blue-text darken-4">Actualizar Doação</h5>
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row">
          <div class="input-field col s12">
            {{ form.name_of_object }}
            <label for="id_name_of_object">Nome do Objeto</label>
          </div>
        </div>
        <div class="row">
          <div class="input-field col s12">
            {{ form.description }}
            <label for="id_description">Descrição</label>
          </div>
          <div class="row">
            <div class="input-field col s12">
              {{ form.status }}
              <label for="id_description">Status</label>
          </div>
        </div>
        <div class="row">
          <div class="file-field input-field col s12">
            <div class="btn blue darken-3">
              <span>Imagem</span>
              {{ form.picture }}
            </div>
            <div class="file-path-wrapper">
              <input class="file-path validate" type="text">
            </div>
          </div>
        </div>
        <div class="row">
          <div class="input-field col s12">
            <select name="{{ form.category.name }}">
              <option value="" disabled selected>Escolha uma categoria</option>
              {% for value, label in form.category.field.choices %}
                  <option value="{{ value }}" {% if value == form.category.value %} selected {% endif %}>{{ label }}</option>
              {% endfor %}
          </select>
              <label for="id_category">Categoria</label>
          </div>
      </div>
        <div class="row">
          <div class="input-field col s12">
              <a href="{% url 'own_donation' %}" class="btn waves-effect waves-light blue darken-3">Cancelar</a>
              <button type="submit" class="btn waves-effect waves-light red darken-3">Actualizar</button>
          </div>
        </div>
      </form>
    </div>
  </div>
  {% endif %}  
  <script>
      document.addEventListener('DOMContentLoaded', function() {
      var selectElems = document.querySelectorAll('select');
      var instances = M.FormSelect.init(selectElems);
  });
  </script>
{% endblock content %}
    

doeja/templates/home/home.html
{% extends 'base.html' %} {% load static %} {% block title%}Doações {% endblock%}
{% block styles %}

<style>
    .card-content {
      height: 100px;
      overflow: hidden;
    }
    
    .card-image {
        object-fit: cover;
        height: 200px;
        width: 100%;
    }
</style>

{% endblock styles %} 
{% block content %}


<div>
  <div class="container">
    <div class="row">
      {% for donation in donations %}
        <div class="col s12 m4">
          <div class="card">
            {% if donation.picture %}
              <div class="card-image">
                <img src="{{ donation.picture.url }}" alt="{{ donation.name_of_object }}">
              </div>
              {% endif %}
              <div class="card-action">
              <span class="text-black h3" style="font-weight: bold; font-size: 28px;">{{ donation.name_of_object }}</span>
              <p>{{ donation.description }}</p>
            </div>
            <div class="card-action">
              <span>Status: {{ donation.get_status_display }}</span>
              <br/>
              <span>Categoria: {{ donation.get_category_display }}</span>
              <span class="right">{{ donation.created_at|date:"d/m/Y" }}</span>
            </div>
            {% if user.is_authenticated %}
              <div class="card-action">
                <a href="{% url 'like_donation' donation_id=donation.id %}">
                  {% if user in donation.likes.all %}
                    <spa class="red-text darken-4">Unlike</spa>
                  {% else %}
                    <spa class="blue-text darken-4">Like</spa>
                  {% endif %}
                </a>
                <span class="right">{{ donation.likes.count }} Likes</span>
              </div>
              <div class="card-action">
                <a href="{% url 'see_and_contact'  id=donation.id%}" class="waves-effect waves-light btn-small blue">Ver e Contactar</a>
              </div>
            {% endif %}
          </div>
        </div>
        {% if forloop.counter|divisibleby:3 and not forloop.last %}
          </div><div class="row">
        {% endif %}
        {% empty %}
        <div class="col s12">
          <div class="card">
            <div class="card-content">
              <span class="card-title">Você ainda não fez nenhuma doação!</span>
              <p>Faça a diferença hoje! Doe e ajude a transformar vidas!</p>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
      <div class="pagination center">
        <ul class="pagination">
            {% if donations.has_previous %}
            <li class="waves-effect"><a href="?page={{ donations.previous_page_number }}"><i class="material-icons">chevron_left</i></a></li>
            {% endif %}

            <span class="current">
              {{ donations.number}} de {{ donations.paginator.num_pages}}
            </span>
    
            {% if donations.has_next %}
            <li class="waves-effect"><a href="?page={{ donations.next_page_number }}"><i class="material-icons">chevron_right</i></a></li>
            {% endif %}
        </ul>
    </div>
    </div>
  </div>
{% endblock content %}

doeja/templates/home/own_donation.html
{% extends 'base.html' %} {% load static %} {% block title%}Doações {% endblock%}
{% block styles %}

<style>
    .card-content {
      height: 100px;
      overflow: hidden;
    }
    
    .card-image {
        object-fit: cover;
        height: 200px;
        width: 100%;
    }
</style>

{% endblock styles %} 
{% block content %}
  <div>
      {% if user.is_authenticated %}
      <div class="col">
          <div class="container">
          <h5 class="blue-text darken-4">Adicionar Doação</h5>
            <form method="post" enctype="multipart/form-data">
              {% csrf_token %}
              <div class="row">
                <div class="input-field col s12">
                  {{ form.name_of_object }}
                  <label for="id_name_of_object">Nome do Objeto</label>
                </div>
              </div>
              <div class="row">
                <div class="input-field col s12">
                  {{ form.description }}
                  <label for="id_description">Descrição</label>
                </div>
                <div class="row">
                  <div class="input-field col s12">
                    {{ form.status }}
                    <label for="id_description">Status</label>
                </div>
              </div>
              <div class="row">
                <div class="file-field input-field col s12">
                  <div class="btn blue darken-3">
                    <span>Imagem</span>
                    {{ form.picture }}
                  </div>
                  <div class="file-path-wrapper">
                    <input class="file-path validate" type="text">
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="input-field col s12">
                  <select name="{{ form.category.name }}">
                    <option value="" disabled selected>Escolha uma categoria</option>
                    {% for value, label in form.category.field.choices %}
                        <option value="{{ value }}" {% if value == form.category.value %} selected {% endif %}>{{ label }}</option>
                    {% endfor %}
                </select>
                    <label for="id_category">Categoria</label>
                </div>
            </div>
              <div class="row">
                <div class="input-field col s12">
                  <button type="submit" class="btn waves-effect waves-light blue darken-3">Adicionar</button>
                </div>
              </div>
            </form>
          </div>
        </div>
    {% endif %}    
    <div class="container">
      <div class="row">
          {% for donation in donations %}
          <div class="col s12 m4">
              <div class="card">
                  {% if donation.picture %}
                  <div class="card-image">
                      <img src="{{ donation.picture.url }}" alt="{{ donation.name_of_object }}">
                  </div>
                  {% endif %}
                  <div class="card-action">
                      <span class="text-black h3" style="font-weight: bold; font-size: 28px;">{{ donation.name_of_object }}</span>
                      <p>{{ donation.description }}</p>
                  </div>
                  <div class="card-action">
                      <span>Categoria: {{ donation.get_category_display }}</span>
                      <span class="right">{{ donation.created_at|date:"d/m/Y" }}</span>
                  </div>
                  {% if user.is_authenticated %}
                  <div class="card-action">
                      <a href="{% url 'like_donation' donation_id=donation.id %}">
                        <a href="#modal-confirm-delete" class="left modal-trigger"><i class="material-icons red-text">delete</i></a>
                        <a href="{% url 'edit_donation' id=donation.id %}" class="left"><i class="material-icons blue-text">update</i></span></a>
                          <span class="right">{{ donation.likes.count }} Likes</span>
                      </a>
                  </div>
                           <!-- Confirmation Modal-->
                  <div id="modal-confirm-delete" class="modal">
                    <div class="modal-content">
                        <h4>Confirmar Exclusão</h4>
                        <p>Tem certeza de que deseja excluir <span style="font-weight: bold;">{{donation.name_of_object}}</span></p>
                    </div>
                    <div class="modal-footer">
                        <a href="#" class="modal-close waves-effect waves-green btn-flat">Cancelar</a>
                        <a href="{% url 'delete_donation' id=donation.id %}" class="waves-effect waves-red btn red">Confirmar</a>
                    </div>
                  {% endif %}
              </div>
          </div>
          {% if forloop.counter|divisibleby:3 and not forloop.last %}
          {% endif %}
          {% empty %}
          <div class="col s12">
              <div class="card">
                  <div class="card-content">
                      <span class="card-title">Você ainda não fez nenhuma doação!</span>
                      <p>Faça a diferença hoje! Doe e ajude a transformar vidas!</p>
                  </div>
              </div>
          </div>
          {% endfor %}
      </div>
    </div>
    
  </div>
<script>
  document.addEventListener('DOMContentLoaded', function() {
      var selectElems = document.querySelectorAll('select');
      var instances = M.FormSelect.init(selectElems);
  });
  document.addEventListener('DOMContentLoaded', function() {
        var modals = document.querySelectorAll('.modal');
        M.Modal.init(modals);
    });
</script>
{% endblock content %}